#!/bin/bash
set -ex

Rscript -e "devtools::install_url(\"https://github.com/upsetjs/upsetjs_r/releases/latest/download/upsetjs.tar.gz\")"
Rscript -e "devtools::install_github(\"https://github.com/lineupjs/lineup_htmlwidget\")"

# Install JupyterLab extension
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension enable --sys-prefix upsetjs_jupyter_widget
jupyter nbextension enable --sys-prefix lineup_widget
jupyter labextension install @jupyter-widgets/jupyterlab-manager@3.0.0-alpha.0 @upsetjs/jupyter_widget lineup_widget
